### ISSUE TITLE
Conform to new API specs

### ISSUE THREAD

**Issue by Tosch110** [LiskHQ/lisk-js#139]
The new API specifics as described here:

https://app.swaggerhub.com/apis/LiskHQ/Lisk/1.0.5

Should be implemented into `lisk-js` before the 1.0.0 release to be prepared.

In order to be reviewed better and more structure this issue will be divided into:

- [x] Erase parseTransaction #239
- [x] Add first parameter GET/POST/PUT for sendRequest #240
- [x] Rewrite popsicle request and erase sendRequestPromise, changeRequest... #241
- [x] Rewrite API functions with new API method #242
- [x] Apart from default parameter, add options object to the API functions #243
- [x] Functions that use GET should be named accordingly (getAccount, getVoters...) #244
- [x] Add missing dapp API functions #290

**Comment by diego-G** [comment]
I am preparing a new version 1.0.6 which is not published yet. I recommend you to wait for it before reviewing this PR.

**Comment by Tosch110** [comment]
In order to be reviewed better and more structure this issue will be divided into:

[ ] Erase parseTransaction #239
[ ] Add first parameter GET/POST/PUT for sendRequest #240
[ ] Rewrite popsicle request and erase sendRequestPromise, changeRequest... #241
[ ] Rewrite API functions with new API method #242
[ ] Apart from default parameter, add options object to the API functions #243
[ ] functions that use GET should be named accordingly (getAccount, getVoters...) #244
