### ISSUE TITLE
Revisit getTransactionBytes refactoring

### ISSUE THREAD

**Issue by willclarktech** [LiskHQ/lisk-js#502]
In 1.0.0 branch
- [x] Fix amount bug for amounts larger than 4 bytes (https://github.com/LiskHQ/lisk-js/issues/544)
- [x] Expand tests (https://github.com/LiskHQ/lisk-js/issues/542)
- [x] Confirm use of Buffer.alloc e.g. in getAssetDataForCreateDappTransaction (https://github.com/LiskHQ/lisk-js/issues/543)
