### ISSUE TITLE
Apply lisk-template

### ISSUE THREAD

**Issue by Tosch110** [LiskHQ/lisk-js#552]
We should apply the `lisk-template` repository created by @LiskHQ/standards to this repository. This will align it with the newly defined standards, patterns and workflows that will be applied to all new and existing repositories from now on.

### Todo

- [x] Update .nvmrc (#568)
- [x] Update .npmrc file (#569)
- [x] Standardize .gitignore file (#570)
- [x] Standardize package.json field (#571)
- [x] Standardize npm scripts  (#572)
- [x] Update Jenkinsfiles to standards (#573)
- [x] Update/Standardize mocha/chai/sinon setup (e.g. sandbox) (#574)
- [x] Update/Standardize package manager (#575)
- [x] Be consistent about use of `should` vs `expect` (#576)
- [x] underscore_separated file/directory names (#577)
- [x] Update ESLint (#578)
- [x] Husky and lint-staged
